baseURL = 'https://bistu-ossdt-2026.github.io/Thegame/'
languageCode = 'zh-cn'
title = 'My New Hugo Project'
theme = 'ananke'

# 让 Ananke 首页能列出 posts _section
SectionPagesMenu = "main"

[params]
  description = "基于 Hugo + Ananke 的技术博客"